server:
  port: 9527

spring:
  application:
    name: JIACHENG-ZUUL-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: jiacheng-zuul-gateway-9527.com
    prefer-ip-address: true

zuul:
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
  routes:
    plat:
      path: /plat/**
      service-id: jiacheng-plat