server:
  port: 8001

spring:
  application:
    name: JIACHENG-PLAT

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: jiacheng-plat-9001.com
    prefer-ip-address: true